version: '3.9'

x-user: &user admin
x-pass: &pass superpupersecret

x-nifi-base: &nifi-base
  image: apache/nifi:1.17.0
  depends_on:
      nifi-toolkit:
        condition: service_completed_successfully
  networks:
    - nifi
  entrypoint:
    - "/bin/bash"
    - "-c"
    - "../scripts/start.sh"

x-nifi-environment: &nifi-environment
  NIFI_CLUSTER_IS_NODE: "true"
  NIFI_ZK_CONNECT_STRING: "zookeeper:2181"
  NIFI_ELECTION_MAX_WAIT: "30 sec"
  NIFI_ELECTION_MAX_CANDIDATES: 1
  NIFI_SENSITIVE_PROPS_KEY: "my-random-string"
  NIFI_CLUSTER_NODE_PROTOCOL_PORT: 8082
  NIFI_WEB_PROXY_HOST: "nifi0:8443,nifi0,nifi1:8443,nifi1,localhost:8080"
  SINGLE_USER_CREDENTIALS_USERNAME: *user
  SINGLE_USER_CREDENTIALS_PASSWORD: *pass
  NIFI_SECURITY_USER_AUTHORIZER: "single-user-authorizer"
  NIFI_SECURITY_USER_LOGIN_IDENTITY_PROVIDER: "single-user-provider"
  INITIAL_ADMIN_IDENTITY: *user
  NIFI_SECURITY_USER_JWS_KEY_ROTATION_PERIOD: 1H
  AUTH: "tls"
  KEYSTORE_TYPE: "JKS"
  KEYSTORE_PASSWORD: supersecretkeystore
  TRUSTSTORE_TYPE: "JKS"
  TRUSTSTORE_PASSWORD: supersecrettruststore


services:
  prometheus:
    image: prom/prometheus:v2.17.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      # - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - 9090:9090
    depends_on:
      - golang-exporter
  
  grafana:
    image: grafana/grafana:6.7.2
    container_name: grafana
    volumes:
      # - grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    
  golang_exporter:
    image: msiedlarek/nifi_exporter:0.2.0
    container_name: golang-exporter
    restart: unless-stopped
    ports:
      - 9103:9103/tcp
    volumes:
      - ./golang_exporter/config.yml:/config/config.yml:ro
    depends_on:
      - nifi0
      - nifi1
    networks:
      - nifi

  python_exporter:
    build: ./python_exporter
    container_name: python_exporter
    ports:
      - 9104:5000/tcp
    environment:
      BASE_URL: https://localhost:8444
      USERNAME: *user
      PASSWORD: *pass
      FLASK_ENV: development
    depends_on:
      - nifi0
      - nifi1
    networks:
      - nifi


  zookeeper:
    image: bitnami/zookeeper:3.8.0
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - nifi

  nifi-toolkit:
    image: apache/nifi-toolkit:1.17.0
    container_name: nifi-toolkit
    user: root
    volumes:
      - nifi_certs:/opt/certs
    entrypoint: ["bash", "-c", "/opt/nifi-toolkit/*/bin/tls-toolkit.sh standalone -o /opt/certs -n nifi[0-1] -P supersecrettruststore -K supersecretkeystore -S supersecretkeystore; chown -R nifi:nifi /opt/certs"]
    networks:
      - nifi

  nifi0:
    <<: *nifi-base
    container_name: nifi0
    ports:
      - 8443:8443
    volumes:
      - nifi_certs:/opt/certs
      - nifi0_conf:/opt/nifi/nifi-current/conf
      - nifi0_extensions:/opt/nifi/nifi-current/extensions
      - nifi0_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi0_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi0_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi0_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi0_state:/opt/nifi/nifi-current/state
      - nifi0_logs:/opt/nifi/nifi-current/logs
    environment:
      <<: *nifi-environment
      NIFI_CLUSTER_ADDRESS: "nifi0"
      NIFI_WEB_HTTPS_HOST: "nifi0"
      NIFI_WEB_HTTPS_PORT: 8443
      KEYSTORE_PATH: "/opt/certs/nifi0/keystore.jks"
      TRUSTSTORE_PATH: "/opt/certs/nifi0/truststore.jks"
    

  nifi1:
    <<: *nifi-base
    container_name: nifi1
    ports:
      - 8444:8444
    volumes:
      - nifi_certs:/opt/certs
      - nifi1_conf:/opt/nifi/nifi-current/conf
      - nifi1_extensions:/opt/nifi/nifi-current/extensions
      - nifi1_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi1_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi1_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi1_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi1_state:/opt/nifi/nifi-current/state
      - nifi1_logs:/opt/nifi/nifi-current/logs
    environment:
      <<: *nifi-environment
      NIFI_CLUSTER_ADDRESS: "nifi1"
      NIFI_WEB_HTTPS_PORT: 8444
      NIFI_WEB_HTTPS_HOST: "nifi1"
      KEYSTORE_PATH: "/opt/certs/nifi1/keystore.jks"
      TRUSTSTORE_PATH: "/opt/certs/nifi1/truststore.jks"


networks:
  nifi:
    driver: bridge

volumes:
  nifi_certs:
  # nifi 0
  nifi0_conf:
  nifi0_extensions:
  nifi0_database_repository:
  nifi0_flowfile_repository:
  nifi0_content_repository:
  nifi0_provenance_repository:
  nifi0_state:
  nifi0_logs:
  # nifi 1
  nifi1_conf:
  nifi1_extensions:
  nifi1_database_repository:
  nifi1_flowfile_repository:
  nifi1_content_repository:
  nifi1_provenance_repository:
  nifi1_state:
  nifi1_logs: