version: '3'

networks:
  app-tier:
    name: talk-streaming-network

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    networks:
      - app-tier
    environment:
      - "ALLOW_ANONYMOUS_LOGIN=yes"

  # nifi1:
  #   image: apache/nifi:1.17.0
  #   container_name: nifi1
  #   ports:
  #     - "8888:8080"
  #     - "8443:8443"
  #   environment:
  #     SINGLE_USER_CREDENTIALS_USERNAME: admin
  #     SINGLE_USER_CREDENTIALS_PASSWORD: superpupersecret
  #     NIFI_WEB_HTTP_HOST: '0.0.0.0'
  #     NIFI_WEB_HTTP_PORT: '8080'
  #     NIFI_WEB_HTTPS_HOST:
  #     NIFI_WEB_HTTPS_PORT:
  #   networks:
  #     - app-tier
  
  # golang_exporter:
  #   image: msiedlarek/nifi_exporter:0.2.0
  #   container_name: golang-exporter
  #   restart: unless-stopped
  #   ports:
  #     - 9103:9103/tcp
  #   volumes:
  #     - ./golang_exporter/config.yml:/config/config.yml:ro
  #   depends_on:
  #     - nifi1
  
  nifi2:
    image: apache/nifi:1.17.0
    container_name: nifi2
    ports:
      - "8889:8080"
      - "8444:8444"
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: superpupersecret
      NIFI_WEB_HTTP_HOST: '0.0.0.0'
      NIFI_WEB_HTTP_PORT: '8080'
      NIFI_WEB_HTTPS_HOST:
      NIFI_WEB_HTTPS_PORT:
    networks:
      - app-tier
  
  python_exporter:
    build: ./python_exporter
    container_name: python-exporter
    ports:
      - 9104:5000/tcp
    environment:
      BASE_URL: https://localhost:8889
      USERNAME: admin
      PASSWORD: superpupersecret 
      FLASK_ENV: development
    depends_on:
      - nifi12
  
  nifi-registry:
    image: apache/nifi-registry:1.17.0
    container_name: nifi-registry
    ports:
      - "18080:18080"
    networks:
      - app-tier
    volumes:
      - ./nifiRegistry/flow-storage:/opt/nifi-registry/nifi-registry-current/flow_storage
      - ./nifiRegistry/database:/opt/nifi-registry/nifi-registry-current/database
  
  