version: '3'

services:
  generator:
    build: ./generator
    container_name: generator
    ports:
      - "5000:5000"
  
  exporter:
    build: ./exporter
    container_name: exporter
    ports:
      - "5000:5000"
    depends_on:
      - generator