global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
# rule_files:
  # - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  # - job_name: 'golangexporter'
  #   scrape_interval: 10s
  #   static_configs:
  #     - targets: ['golang_exporter:9103']

  - job_name: 'pythonexporter'
    scrape_interval: 10s
    # dns_sd_configs:
      # - names:
          # - python_exporter
        # port: 9104
    static_configs:
      - targets: ['192.168.50.150:9104']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

# alerting:
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets: 
#       - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']